package main

WINDOW_WIDTH :: 1200
WINDOW_HEIGHT :: 800
GRID_WIDTH :: 36
GRID_HEIGHT :: 36
FPS :: 60
TEXTURE_WIDTH :: 64
TEXTURE_HEIGHT :: 64
MAP_TEXTURE_SIZE :: 256.0
CHARACTER_TEXTURE_SIZE :: 350.0
CHARACTER_MOVEMENT_INTERVAL :: 0.20
ENEMY_MOVEMENT_INTERVAL :: 0.40
CHARACTER_POSE_INTERVAL :: 0.20
ENEMY_POSE_INTERVAL :: 0.10
ENEMY_TEXTURE_SIZE :: 256.0
NEW_HIGH_SCORES_TEXT :: "{\n\t\"easy\":\t0,\n\t\"medium\":\t0, \n\t\"hard\":\t0\n}"
